import Link from 'next/link';
import styles from './page.module.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

//any code defined in this file is displayed in every single page, like a global navbar, and footer
//I think this layout file can be made again in a sub-directory and will only be applied to the children of that route

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <main>
          <nav className={styles.nav}>
            <Link href='/'>Home</Link>
            <Link href='/dogfacts'>Dog Facts</Link>
            <Link href='/weather'>Weather</Link>
          </nav>
        </main>
        {children}
      </body>
    </html>
  );
}
